"""
Coordinates from
https://docs.google.com/spreadsheets/d/1q45g7Su1dc6tUyMNBNJ1hmr5A_Ddavklg2vbTgG2K90/edit#gid=0
"""

LOCATIONS = {
    "SYDNEY": {
        "accuweather_location_key": 12481,
        "bom.gov.au": "http://www.bom.gov.au/places/nsw/sydney/forecast/detailed/",
        "coordinates": (-33.86, 151.21),
        "timezone": "Australia/Sydney",
    },
    "MELBOURNE": {
        "accuweather_location_key": 3497808,
        "bom.gov.au": "http://www.bom.gov.au/places/vic/KFWX/forecast/detailed/",
        "coordinates": (-37.83, 144.98),
        "timezone": "Australia/Melbourne",
    },
    "BRISBANE": {
        "accuweather_location_key": 1404,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/brisbane/forecast/detailed/",
        "coordinates": (-27.48, 153.04),
        "timezone": "Australia/Brisbane",
    },
    "ADELAIDE AIRPORT": {
        "accuweather_location_key": 3496965,
        "bom.gov.au": "http://www.bom.gov.au/places/sa/KHE9/forecast/detailed/",
        "coordinates": (-34.95, 138.52),
        "timezone": "Australia/Adelaide",
    },
    "ALBURY": {
        "accuweather_location_key": 3497251,
        "bom.gov.au": "http://www.bom.gov.au/places/nsw/albury/forecast/detailed/",
        "coordinates": (-36.07, 146.95),
        "timezone": "Australia/Sydney",
    },
    "AVALON": {
        "accuweather_location_key": 3497572,
        "bom.gov.au": "http://www.bom.gov.au/places/vic/avalon/forecast/detailed/",
        "coordinates": (-38.03, 144.48),
        "timezone": "Australia/Sydney",
    },
    "BALLARAT": {
        "accuweather_location_key": 3497441,
        "bom.gov.au": "http://www.bom.gov.au/places/vic/KFCW/forecast/detailed/",
        "coordinates": (-37.51, 143.79),
        "timezone": "Australia/Sydney",
    },
    "BENDIGO": {
        "accuweather_location_key": 3493875,
        "bom.gov.au": "http://www.bom.gov.au/places/vic/bendigo/forecast/detailed/",
        "coordinates": (-36.74, 144.33),
        "timezone": "Australia/Melbourne",
    },
    "BUNBURY": {
        "accuweather_location_key": 3493156,
        "bom.gov.au": "http://www.bom.gov.au/places/wa/bunbury/forecast/detailed/",
        "coordinates": (-33.36, 115.64),
        "timezone": "Australia/Perth",
    },
    "CAIRNS": {
        "accuweather_location_key": 3494520,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/cairns/forecast/detailed/",
        "coordinates": (-16.87, 145.75),
        "timezone": "Australia/Brisbane",
    },
    "CANBERRA": {
        "accuweather_location_key": 3497116,
        "bom.gov.au": "http://www.bom.gov.au/places/act/canberra/forecast/detailed/",
        "coordinates": (-35.31, 149.2),
        "timezone": "Australia/Sydney",
    },
    "CANUNGRA": {
        "accuweather_location_key": 3495452,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/witheren/forecast/detailed/",
        "coordinates": (-28.04, 153.19),
        "timezone": "Australia/Brisbane",
    },
    "COLDSTREAM": {
        "accuweather_location_key": 16352,
        "bom.gov.au": "http://www.bom.gov.au/places/vic/M4BD/forecast/detailed/",
        "coordinates": (-37.72, 145.41),
        "timezone": "Australia/Melbourne",
    },
    "COOMA AIRPORT": {
        "accuweather_location_key": 13627,
        "bom.gov.au": "http://www.bom.gov.au/places/nsw/M7XQ/forecast/detailed/",
        "coordinates": (-36.29, 148.97),
        "timezone": "Australia/Sydney",
    },
    "DARWIN AIRPORT": {
        "accuweather_location_key": 3494423,
        "bom.gov.au": "http://www.bom.gov.au/places/nt/G4ES/forecast/detailed/",
        "coordinates": (-12.42, 130.89),
        "timezone": "Australia/Darwin",
    },
    "DUNALLEY": {
        "accuweather_location_key": 20090,
        "bom.gov.au": "http://www.bom.gov.au/places/tas/dunalley/forecast/detailed/",
        "coordinates": (-42.9, 147.79),
        "timezone": "Australia/Hobart",
    },
    "GEELONG RACECOURSE": {
        "accuweather_location_key": 15814,
        "bom.gov.au": "http://www.bom.gov.au/places/vic/geelong/forecast/detailed/",
        "coordinates": (-38.17, 144.38),
        "timezone": "Australia/Melbourne",
    },
    "GEORGETOWN AIRPORT": {
        "accuweather_location_key": 14185,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/georgetown/forecast/detailed/",
        "coordinates": (-18.3, 143.53),
        "timezone": "Australia/Hobart",
    },
    "GOLD COAST SEAWAY": {
        "accuweather_location_key": 3495430,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/gold-coast-seaway/forecast/detailed/",
        "coordinates": (-27.94, 153.43),
        "timezone": "Australia/Brisbane",
    },
    "GREEN CAPE": {
        "accuweather_location_key": 3493966,
        "bom.gov.au": "http://www.bom.gov.au/places/nsw/ME5G/forecast/detailed/",
        "coordinates": (-37.26, 150.05),
        "timezone": "Australia/Sydney",
    },
    "GROVE": {
        "accuweather_location_key": 19892,
        "bom.gov.au": "http://www.bom.gov.au/places/tas/huonville/forecast/detailed/",
        "coordinates": (-42.99, 147.07),
        "timezone": "Australia/Hobart",
    },
    "HOBART": {
        "accuweather_location_key": 25619,
        "bom.gov.au": "http://www.bom.gov.au/places/tas/hobart/forecast/detailed/",
        "coordinates": (-42.89, 147.33),
        "timezone": "Australia/Hobart",
    },
    "LAUNCESTON": {
        "accuweather_location_key": 1607175,
        "bom.gov.au": "http://www.bom.gov.au/places/tas/riverside/forecast/detailed/",
        "coordinates": (-41.42, 147.12),
        "timezone": "Australia/Hobart",
    },
    "MACKAY": {
        "accuweather_location_key": 3494768,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/TT0Q/forecast/detailed/",
        "coordinates": (-21.12, 149.22),
        "timezone": "Australia/Brisbane",
    },
    "MAITLAND AIRPORT": {
        "accuweather_location_key": 17459,
        "bom.gov.au": "http://www.bom.gov.au/places/nsw/rutherford/forecast/detailed/",
        "coordinates": (-32.7, 151.49),
        "timezone": "Australia/Sydney",
    },
    "MANDURAH": {
        "accuweather_location_key": 21840,
        "bom.gov.au": "http://www.bom.gov.au/places/wa/3N5F/forecast/detailed/",
        "coordinates": (-32.52, 115.71),
        "timezone": "Australia/Perth",
    },
    "MELBOURNE AIRPORT": {
        "accuweather_location_key": 3497482,
        "bom.gov.au": "http://www.bom.gov.au/places/vic/tullamarine/forecast/detailed/",
        "coordinates": (-37.67, 144.83),
        "timezone": "Australia/Melbourne",
    },
    "NARRABRI": {
        "accuweather_location_key": 13152,
        "bom.gov.au": "http://www.bom.gov.au/places/nsw/narrabri/forecast/detailed/",
        "coordinates": (-30.32, 149.83),
        "timezone": "Australia/Sydney",
    },
    "NARRANDERA AIRPORT": {
        "accuweather_location_key": 12770,
        "bom.gov.au": "http://www.bom.gov.au/places/nsw/MHTN/forecast/detailed/",
        "coordinates": (-34.7, 146.51),
        "timezone": "Australia/Sydney",
    },
    "NEWCASTLE NOBBYS": {
        "accuweather_location_key": 12777,
        "bom.gov.au": "http://www.bom.gov.au/places/nsw/newcastle/forecast/detailed/",
        "coordinates": (-32.92, 151.8),
        "timezone": "Australia/Sydney",
    },
    "PERTH": {
        "accuweather_location_key": 16533,
        "bom.gov.au": "http://www.bom.gov.au/places/wa/dianella/forecast/detailed/",
        "coordinates": (-31.92, 115.87),
        "timezone": "Australia/Perth",
    },
    "ROCKHAMPTON": {
        "accuweather_location_key": 24719,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/rockhampton/forecast/detailed/",
        "coordinates": (-23.38, 150.48),
        "timezone": "Australia/Brisbane",
    },
    "TOOWOOMBA": {
        "accuweather_location_key": 3492316,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/toowoomba/forecast/detailed/",
        "coordinates": (-27.54, 151.91),
        "timezone": "Australia/Brisbane",
    },
    "TOWNSVILLE": {
        "accuweather_location_key": 3494648,
        "bom.gov.au": "http://www.bom.gov.au/places/qld/townsville/forecast/detailed/",
        "coordinates": (-19.25, 146.77),
        "timezone": "Australia/Brisbane",
    },
}
